apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumememory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumememory-app
  template:
    metadata:
      labels:
        app: consumememory-app
    spec:
      containers:
        - name: consumememory
          image: consumememory-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: JAVA_OPTS
              value: "-Xms192m -Xmx448m"
